import type { SupabaseClient } from "@supabase/supabase-js";

import { getSupabase } from "@/lib/supabase";
import type { Database, PaymentReceiptRow } from "@/types/database";
import { BaseRepository } from "./BaseRepository";

/**
 * `payment_receipts` repository — metadata for uploaded receipt files
 * (Phase 3). The binary content lives in a PRIVATE Supabase Storage bucket;
 * this table only records `storage_path`, filename, and MIME type. Raw paths
 * are never exposed to customers — admins access files through short-lived
 * signed URLs generated by the storage layer.
 */
export class PaymentReceiptsRepository extends BaseRepository<"payment_receipts"> {
  constructor(client: SupabaseClient<Database> = getSupabase()) {
    super(client, "payment_receipts");
  }

  /** The receipt attached to a payment, if any. */
  findByPayment(paymentId: string): Promise<PaymentReceiptRow | null> {
    return this.findOneBy({ payment_id: paymentId });
  }
}
