/**
 * Example payloads attached to schemas so Swagger UI renders sample data.
 * Values are representative of the live dataset (e.g. bank code ABY).
 */

export const apiExamples = {
  bank: {
    bank_code: "ABY",
    bank_name: "Awash Bank",
    bank_type: "private",
    source_url: "https://www.awashbank.com/exchange-rate",
    is_active: true,
    created_at: "2026-01-15T09:30:00.000Z",
    total_assets: 213_000_000_000,
    total_deposite: 171_000_000_000,
    total_branches: 846,
    total_employee: 9_200,
    loan_to_deposite_ratio: 0.61,
    return_on_asset: 0.035,
    return_on_equity: 0.28,
    profit_before_tax: 15_000_000_000,
    profit_after_tax: 12_000_000_000,
    retained_earning: 8_000_000_000,
    paid_up_capital: 22_000_000_000,
    reserves: 6_000_000_000,
    total_liabilities: 191_000_000_000,
  },
  exchangeRate: {
    id: "c8f21ffd-9c80-46fa-828d-69bf5d89eb78",
    bank_code: "ABY",
    currency_code: "USD",
    buying_rate: 123.45,
    selling_rate: 124.55,
    transactional_buying: null,
    transactional_selling: null,
    weighted_avg_buying: null,
    weighted_avg_selling: null,
    rate_date: "2026-08-02",
    source: "SCRAPER",
    scraped_at: "2026-08-02T08:00:00.000Z",
    stale: false,
    change: 0.42,
  },
  rateDateRange: {
    min: "2026-07-01",
    max: "2026-08-02",
  },
  manualRate: {
    id: "3fbf920e-2cf7-47d2-95d7-80b29d9a00d7",
    bank_code: "ABY",
    currency_code: "USD",
    buying_rate: 123.4,
    selling_rate: 124.4,
    transactional_buying: 125.1,
    transactional_selling: 126.2,
    rate_date: "2026-08-02",
    entered_by: null,
    note: "Adjusted after market open.",
    created_at: "2026-08-02T09:05:00.000Z",
  },
  manualRateInput: {
    bank_code: "ABY",
    currency_code: "USD",
    buying_rate: 123.4,
    selling_rate: 124.4,
    transactional_buying: 125.1,
    transactional_selling: 126.2,
    rate_date: "2026-08-02",
    note: "Adjusted after market open.",
    entered_by: null,
  },
  scraperHealth: {
    bank_code: "ABY",
    status: "healthy",
    consecutive_failures: 0,
    last_success: "2026-08-02T08:00:00.000Z",
    last_failure: null,
    last_rate_date: "2026-08-02",
    response_time_ms: 1820,
    updated_at: "2026-08-02T08:00:00.000Z",
  },
  scraperHealthSummary: {
    total: 29,
    healthy: 27,
    degraded: 1,
    failed: 1,
    unknown: 0,
    averageResponseTimeMs: 1520,
    averageConsecutiveFailures: 0.3,
    staleCount: 12,
  },
  scrapeLog: {
    id: "dc9f919f-cc93-421e-9163-0669713f8723",
    run_id: "3fbf920e-2cf7-47d2-95d7-80b29d9a00d7",
    bank_code: "ABY",
    status: "success",
    scenario: "updated",
    currencies_count: 23,
    error_message: null,
    duration_ms: 1820,
    ran_at: "2026-08-02T08:00:00.000Z",
  },
  adminProfile: {
    name: "Root Admin",
    email: "admin@ethioexchangehub.com",
    role: "super_admin",
    initials: "RA",
    memberSince: "2026-01-01",
    lastLogin: "2026-08-01T08:00:00.000Z",
  },
  adminSettings: {
    siteName: "Ethio Exchange Hub",
    defaultCurrency: "USD",
    refreshInterval: "15m",
    timezone: "Africa/Addis_Ababa",
    retentionDays: "30",
    emailAlerts: false,
    failureAlerts: false,
    dailyDigest: false,
    weeklyReport: false,
  },
  rateTrendPoint: {
    label: "2026-08-02",
    cashBuying: 120.25,
    cashSelling: 121.35,
  },
  contactMessage: {
    id: "a1b2c3d4-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
    name: "Abebe Kebede",
    email: "abebe@example.com",
    subject: "Question about historical rates",
    message: "Hello, could you share how far back the historical rate data goes?",
    created_at: "2026-08-02T09:05:00.000Z",
  },
  contactMessageInput: {
    name: "Abebe Kebede",
    email: "abebe@example.com",
    subject: "Question about historical rates",
    message: "Hello, could you share how far back the historical rate data goes?",
  },
  featuredContent: {
    id: "0f3f8b3e-1c2d-4e5f-8a9b-0c1d2e3f4a5b",
    title: "Awash Bank — Back-to-School Offer",
    description: "Student account promotions for the new term.",
    image_url: "https://cdn.example.com/awash-school.jpg",
    advertiser_name: "Awash Bank",
    badge_text: "SPONSORED",
    cta_text: "View Offer",
    destination_url: "/offers/awash-school",
    destination_type: "internal",
    image_alt: "Awash Bank back-to-school promotion",
    is_active: true,
    display_order: 0,
    start_at: null,
    end_at: null,
    created_by: null,
    feature_1_icon: "graduation-cap",
    feature_1_title: "Zero balance",
    feature_1_description: "No minimum balance required.",
    feature_2_icon: "percentage",
    feature_2_title: "5% cashback",
    feature_2_description: "On all card payments.",
    feature_3_icon: null,
    feature_3_title: null,
    feature_3_description: null,
    created_at: "2026-08-01T09:00:00.000Z",
    updated_at: "2026-08-01T09:00:00.000Z",
  },
  activeFeaturedContent: {
    id: "0f3f8b3e-1c2d-4e5f-8a9b-0c1d2e3f4a5b",
    title: "Awash Bank — Back-to-School Offer",
    description: "Student account promotions for the new term.",
    image_url: "https://cdn.example.com/awash-school.jpg",
    image_alt: "Awash Bank back-to-school promotion",
    advertiser_name: "Awash Bank",
    badge_text: "SPONSORED",
    cta_text: "View Offer",
    destination_url: "/offers/awash-school",
    destination_type: "internal",
    features: [
      {
        icon: "graduation-cap",
        title: "Zero balance",
        description: "No minimum balance required.",
      },
      { icon: "percentage", title: "5% cashback", description: "On all card payments." },
    ],
  },
  featuredContentInput: {
    title: "Awash Bank — Back-to-School Offer",
    description: "Student account promotions for the new term.",
    image_url: "https://cdn.example.com/awash-school.jpg",
    advertiser_name: "Awash Bank",
    badge_text: "SPONSORED",
    cta_text: "View Offer",
    destination_url: "/offers/awash-school",
    destination_type: "internal",
    image_alt: "Awash Bank back-to-school promotion",
    is_active: true,
    display_order: 0,
    start_at: null,
    end_at: null,
    feature_1_icon: "graduation-cap",
    feature_1_title: "Zero balance",
    feature_1_description: "No minimum balance required.",
  },
} as const;
